name: IPTV List Güncelleyici

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik çalışır
  workflow_dispatch: # İstediğin zaman manuel başlatabilmen için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repoyu Çek
      uses: actions/checkout@v3

    - name: Node.js Kur
      uses: actions/setup-node@v3
      with:
        node-node-version: '18'

    - name: Bağımlılıkları Yükle
      run: npm install axios

    - name: Botu Çalıştır
      run: node bot.js

    - name: Değişiklikleri Kaydet ve Gönder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add turkce.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Kanal listesi güncellendi" && git push)
